name: 'Linguist'
description: 'This action detects languages in provided repository and give it to you in output'
inputs:
  path:
    description: 'Path to the repository'
    required: false
    default: './'
  percentage:
    description: 'Output will be in percentage format, e.g. {"Python":"100%"}. By default it is in fractions, e.g. {"Python":1.0}. Default: false.'
    required: false
    default: false
outputs:
  data:
    description: 'Result of the output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.percentage }}