name: 'Linguist'
description: 'This action detects languages in provided repository and give it to you in output'
inputs:
  path:
    description: 'Path to the repository'
    required: false
    default: './'
outputs:
  data:
    description: 'Result of the output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}