---
name: CI (latest)

on: push
  # push:
  #   tags:
  #     - 'v*.*.*'

jobs:
  functional_tests:
    name: Functional tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          ref: v1.0.0
      - uses: fabasoad/linguist-action@v1.0.0
        id: linguist
        with:
          path: './'
          percentage: true
      - name: Validate linguist result
        run: |
          [[ '{"Ruby":"75.21%","Dockerfile":"19.80%","Shell":"5.00%"}' == '${{ steps.linguist.outputs.data }}' ]] || exit 1;
