---
name: CI (main)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  functional_tests:
    name: Functional tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: ./
        id: linguist
        with:
          percentage: true
      - name: Validate linguist result
        run: |
          [[ '{"Ruby":"76.68%","Dockerfile":"19.31%","Shell":"4.01%"}' == '${{ steps.linguist.outputs.data }}' ]] || exit 1;
