name: Ruby Lint

on: push
#   push:
#     paths:
#       - '**.rb'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: adwerx/pronto-ruby@v2.2.0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
